version: "3.9"

services:
  postgres:
    image: postgres:17
    container_name: postgres17
    environment:
      POSTGRES_DB: etl_db
      POSTGRES_USER: etl_user
      POSTGRES_PASSWORD: etl_pass
    ports:
      - "5432:5432"
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U etl_user -d etl_db"]
      interval: 5s
      timeout: 5s
      retries: 5
    
  etl:
    build: ./etl
    container_name: etl_runner
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: etl_db
      DB_USER: etl_user
      DB_PASSWORD: etl_pass
    command: ["bash", "/app/run_etl.sh"]

volumes:
  pgdata: